apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-caller
  labels:
    app: caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller
  template:
    metadata:
      labels:
        app: caller
    spec:
      containers:
        - name: microservice-caller
          image: alpine:latest
          command: ["/bin/sh", "-c", "apk add --no-cache curl && sh /scripts/call-nginx.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-script
