apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hi Veeva! Welcome to NGINX!</title>
    </head>
    <body>
        <h1>Hello from NGINX running in Kubernetes!</h1>
    </body>
    </html>
